(define-library (compiler reader lexer)
  (import (scheme base)
	  (compiler utils regex)
	  (compiler utils lexer)
	  (compiler utils scanner)
	  (streams))
  (export r4rs-lex
	  test-r4rs-lex)
  ;(include "./lexer/spec.scm")
  (include "./lexer/r4rs.scm"))
